import type {
  BeautyApplicationStep,
  BeautyLook,
  BeautyProduct,
} from "./types";

export const BEAUTY_PRODUCTS: readonly BeautyProduct[] = [
  {
    id: "beauty-product-skin-torriden",
    brand: "토리든 (Torriden)",
    name: "다이브인 저분자 히알루론산 수분 세럼 50ml",
    shade: "투명 수분 베이스",
    image: "/products/kb-torriden-serum.jpg",
    price: 18000,
    retailer: "올리브영 공식 스토어",
    url: "https://www.oliveyoung.co.kr",
    similarIds: ["beauty-product-skin-dalba"],
  },
  {
    id: "beauty-product-skin-dalba",
    brand: "달바 (d'Alba)",
    name: "화이트 트러플 퍼스트 스프레이 세럼 100ml",
    shade: "비건 글로우 미스트",
    image: "/products/kb-dalba-serum.jpg",
    price: 29900,
    retailer: "달바 공식 브랜드관",
    url: "https://dalba.co.kr",
    similarIds: ["beauty-product-skin-torriden"],
  },
  {
    id: "beauty-product-base-clio",
    brand: "클리오 (CLIO)",
    name: "킬커버 더 뉴 파운웨어 쿠션 기획세트 (본품+리필)",
    shade: "03 리넨 (21호 내추럴 옐로우 베이지)",
    image: "/products/kb-clio-cushion.jpg",
    price: 24500,
    retailer: "클럽클리오 공식몰",
    url: "https://clubclio.co.kr",
    similarIds: ["beauty-product-base-roundlab"],
  },
  {
    id: "beauty-product-base-roundlab",
    brand: "라운드랩 (ROUND LAB)",
    name: "자작나무 수분 선크림 50ml + 클렌저 세트",
    shade: "수분 밀착 베이스",
    image: "/products/kb-roundlab-cream.jpg",
    price: 19500,
    retailer: "올리브영 단독기획",
    url: "https://www.oliveyoung.co.kr",
    similarIds: ["beauty-product-base-clio"],
  },
  {
    id: "beauty-product-eye-palette",
    brand: "투쿨포스쿨 (Too Cool For School)",
    name: "아트클래스 바이로댕 쉐딩 & 아이 음영 듀오",
    shade: "01 클래식 웜 뉴트럴",
    image: "/products/kb-toocool-shading.jpg",
    price: 12000,
    retailer: "투쿨포스쿨 공식 스토어",
    url: "https://www.toocoolforschool.com",
    similarIds: ["beauty-product-eye-glint"],
  },
  {
    id: "beauty-product-eye-glint",
    brand: "글린트 (Glint)",
    name: "하이라이터 듀이 문 4g",
    shade: "01 듀이 문 (샴페인 베이지)",
    image: "/products/kb-glint-highlighter.jpg",
    price: 17600,
    retailer: "글린트 공식몰",
    url: "https://glintcosmetics.com",
    similarIds: ["beauty-product-eye-palette"],
  },
  {
    id: "beauty-product-cheek-3ce",
    brand: "3CE (쓰리씨이)",
    name: "무드 레시피 페이스 블러쉬",
    shade: "ROSE BEIGE (수채화 핑크 로즈)",
    image: "/products/kb-3ce-blush.jpg",
    price: 17000,
    retailer: "스타일난다 공식 스토어",
    url: "https://stylenanda.com",
    similarIds: ["beauty-product-cheek-peripera"],
  },
  {
    id: "beauty-product-cheek-peripera",
    brand: "페리페라 (Peripera)",
    name: "맑게 물든 선샤인 치크",
    shade: "02 밀크티 한잔해",
    image: "/products/kb-3ce-blush.jpg",
    price: 7000,
    retailer: "올리브영 공식 스토어",
    url: "https://www.oliveyoung.co.kr",
    similarIds: ["beauty-product-cheek-3ce"],
  },
  {
    id: "beauty-product-lip-romand",
    brand: "롬앤 (Rom&nd)",
    name: "쥬시 래스팅 틴트 (글래스 립 컬렉션)",
    shade: "#23 누카다미아 (Nucadamia)",
    image: "/products/kb-romand-tint.jpg",
    price: 13900,
    retailer: "롬앤 공식 브랜드 스토어",
    url: "https://romand.co.kr",
    similarIds: [
      "beauty-product-lip-22",
      "beauty-product-lip-24",
      "beauty-product-lip-25",
    ],
  },
  {
    id: "beauty-product-lip-22",
    brand: "롬앤 (Rom&nd)",
    name: "쥬시 래스팅 틴트",
    shade: "#22 포멜로 스킨 (Pomelo Skin)",
    image: "/products/kb-romand-tint.jpg",
    price: 13900,
    retailer: "롬앤 공식 브랜드 스토어",
    url: "https://romand.co.kr",
    similarIds: ["beauty-product-lip-romand", "beauty-product-lip-24"],
  },
  {
    id: "beauty-product-lip-24",
    brand: "롬앤 (Rom&nd)",
    name: "쥬시 래스팅 틴트",
    shade: "#24 필링 앵두 (Peeling Angdoo)",
    image: "/products/kb-romand-tint.jpg",
    price: 13900,
    retailer: "롬앤 공식 브랜드 스토어",
    url: "https://romand.co.kr",
    similarIds: ["beauty-product-lip-romand", "beauty-product-lip-25"],
  },
  {
    id: "beauty-product-lip-25",
    brand: "롬앤 (Rom&nd)",
    name: "쥬시 래스팅 틴트",
    shade: "#25 베어 그레이프 (Bare Grape)",
    image: "/products/kb-romand-tint.jpg",
    price: 13900,
    retailer: "롬앤 공식 브랜드 스토어",
    url: "https://romand.co.kr",
    similarIds: ["beauty-product-lip-romand", "beauty-product-lip-24"],
  },
] as const;

export const BEAUTY_STEPS: readonly BeautyApplicationStep[] = [
  {
    id: "beauty-step-skin",
    order: 1,
    region: "skin",
    label: "SKIN 단계 · 수분 레이어링",
    startTime: 0,
    endTime: 8,
    productId: "beauty-product-skin-torriden",
    amount: "스포이드 2방울",
    method: "손바닥 온도로 얼굴 전체를 지그시 감싸 밀착 흡수",
    applicationArea: "양 볼 안쪽부터 이마, 턱선 전면",
    layerCount: 2,
    hotspot: { x: 0.28, y: 0.28, w: 0.44, h: 0.38 },
  },
  {
    id: "beauty-step-base",
    order: 2,
    region: "base",
    label: "BASE 단계 · 킬커버 밀착 쿠션",
    startTime: 9,
    endTime: 16,
    productId: "beauty-product-base-clio",
    amount: "퍼프 반 펌프 균일량",
    method: "결 방향으로 가볍게 두드리며 모공 요철 커버",
    applicationArea: "나비존 중심 얇은 1차 도포 후 T존 마무리",
    layerCount: 1,
    hotspot: { x: 0.3, y: 0.35, w: 0.4, h: 0.35 },
  },
  {
    id: "beauty-step-eye",
    order: 3,
    region: "eye",
    label: "EYE 단계 · 내추럴 음영 컨투어",
    startTime: 17,
    endTime: 24,
    productId: "beauty-product-eye-palette",
    amount: "사선 브러시 1회 터치",
    method: "아이홀 중앙에서 눈꼬리 방향으로 자연스럽게 블렌딩",
    applicationArea: "눈두덩이 음영 홀 및 애교살 라인",
    layerCount: 2,
    hotspot: { x: 0.32, y: 0.32, w: 0.36, h: 0.12 },
  },
  {
    id: "beauty-step-cheek",
    order: 4,
    region: "cheek",
    label: "CHEEK 단계 · 수채화 생기 블러셔",
    startTime: 25,
    endTime: 32,
    productId: "beauty-product-cheek-3ce",
    amount: "원형 브러시 2회 굴리기",
    method: "광대 중앙에서 관자놀이 방향으로 사선 리프팅 블렌딩",
    applicationArea: "애플존 중심 자연스러운 혈색 연출",
    layerCount: 1,
    hotspot: { x: 0.22, y: 0.44, w: 0.56, h: 0.18 },
  },
  {
    id: "beauty-step-lip",
    order: 5,
    region: "lip",
    label: "LIP 단계 · 너티 글래스 립",
    startTime: 33,
    endTime: 42,
    productId: "beauty-product-lip-romand",
    amount: "어플리케이터 팁 1회분",
    method: "1 Full coat 전체 도포 후 안쪽 중심 center reapply",
    applicationArea: "입술 전체 베이스 후 안쪽 레이어링 그라데이션",
    layerCount: 2,
    hotspot: { x: 0.41, y: 0.58, w: 0.18, h: 0.12 },
  },
] as const;

export const BEAUTY_DEMO_LOOK: BeautyLook = {
  id: "beauty-demo-curated-look",
  creatorName: "은서",
  creatorHandle: "@edit.eunseo",
  avatar: "/kbeauty-models/kb-creator-01.jpg",
  caption: "동남아 K-뷰티 투명 글래스 스킨 & 너티 글로우 립 튜토리얼 ✨ 완성된 룩에서 궁금한 부위를 터치하면 실제 사용 과정과 제품을 확인하고 바로 구매할 수 있어요.",
  videoSrc: "/kbeauty-models/model-glow-lip.jpg", // 포스터 및 visual fallback
  posterSrc: "/kbeauty-models/model-glow-lip.jpg",
  finalLookStart: 0,
  finalLookEnd: 5,
  steps: BEAUTY_STEPS,
} as const;
