import type {
  BeautyApplicationStep,
  BeautyLook,
  BeautyProduct,
} from "./types";

const PENDING_INFORMATION = "정보 확인 필요";

export const BEAUTY_PRODUCTS: readonly BeautyProduct[] = [
  {
    id: "beauty-product-skin-pending",
    brand: PENDING_INFORMATION,
    name: PENDING_INFORMATION,
    shade: PENDING_INFORMATION,
    image: null,
    price: null,
    retailer: null,
    url: null,
    similarIds: [],
  },
  {
    id: "beauty-product-base-pending",
    brand: PENDING_INFORMATION,
    name: PENDING_INFORMATION,
    shade: PENDING_INFORMATION,
    image: null,
    price: null,
    retailer: null,
    url: null,
    similarIds: [],
  },
  {
    id: "beauty-product-eye-pending",
    brand: PENDING_INFORMATION,
    name: PENDING_INFORMATION,
    shade: PENDING_INFORMATION,
    image: null,
    price: null,
    retailer: null,
    url: null,
    similarIds: [],
  },
  {
    id: "beauty-product-cheek-pending",
    brand: PENDING_INFORMATION,
    name: PENDING_INFORMATION,
    shade: PENDING_INFORMATION,
    image: null,
    price: null,
    retailer: null,
    url: null,
    similarIds: [],
  },
  {
    id: "beauty-product-lip-pending",
    brand: PENDING_INFORMATION,
    name: PENDING_INFORMATION,
    shade: PENDING_INFORMATION,
    image: null,
    price: null,
    retailer: null,
    url: null,
    similarIds: [],
  },
] as const;

export const BEAUTY_STEPS: readonly BeautyApplicationStep[] = [
  {
    id: "beauty-step-skin-pending",
    order: null,
    region: "skin",
    label: "SKIN 단계 · 정보 확인 필요",
    startTime: null,
    endTime: null,
    productId: "beauty-product-skin-pending",
    amount: PENDING_INFORMATION,
    method: PENDING_INFORMATION,
    applicationArea: PENDING_INFORMATION,
    layerCount: null,
    hotspot: null,
  },
  {
    id: "beauty-step-base-pending",
    order: null,
    region: "base",
    label: "BASE 단계 · 정보 확인 필요",
    startTime: null,
    endTime: null,
    productId: "beauty-product-base-pending",
    amount: PENDING_INFORMATION,
    method: PENDING_INFORMATION,
    applicationArea: PENDING_INFORMATION,
    layerCount: null,
    hotspot: null,
  },
  {
    id: "beauty-step-eye-pending",
    order: null,
    region: "eye",
    label: "EYE 단계 · 정보 확인 필요",
    startTime: null,
    endTime: null,
    productId: "beauty-product-eye-pending",
    amount: PENDING_INFORMATION,
    method: PENDING_INFORMATION,
    applicationArea: PENDING_INFORMATION,
    layerCount: null,
    hotspot: null,
  },
  {
    id: "beauty-step-cheek-pending",
    order: null,
    region: "cheek",
    label: "CHEEK 단계 · 정보 확인 필요",
    startTime: null,
    endTime: null,
    productId: "beauty-product-cheek-pending",
    amount: PENDING_INFORMATION,
    method: PENDING_INFORMATION,
    applicationArea: PENDING_INFORMATION,
    layerCount: null,
    hotspot: null,
  },
  {
    id: "beauty-step-lip-pending",
    order: null,
    region: "lip",
    label: "LIP 단계 · 정보 확인 필요",
    startTime: null,
    endTime: null,
    productId: "beauty-product-lip-pending",
    amount: PENDING_INFORMATION,
    method: PENDING_INFORMATION,
    applicationArea: PENDING_INFORMATION,
    layerCount: null,
    hotspot: null,
  },
] as const;

export const BEAUTY_DEMO_LOOK: BeautyLook = {
  id: "beauty-demo-curated-look",
  creatorName: "크리에이터 정보 확인 필요",
  creatorHandle: "계정 정보 확인 필요",
  avatar: null,
  caption: "캡션 정보 확인 필요",
  videoSrc: "/beauty-demo/creator-makeup.mp4",
  posterSrc: "/beauty-demo/poster.jpg",
  finalLookStart: null,
  finalLookEnd: null,
  steps: BEAUTY_STEPS,
} as const;
