import type { KeycapDefinition } from "./keycap-types";

export const KEYCAPS = [
  { id: "kcap-milk-1", name: "Milk One", collection: "Milk", rarity: "common", material: "PBT", sound: "creamy", size: "1U", profile: "Cherry", color: "#f9f0e7", accent: "#d9c2b5", legend: "Press", icon: "◌", description: "Warm ivory top with a soft satin body.", unlockCondition: "Starter cap", unlockPresses: 0 },
  { id: "kcap-milk-2", name: "Milk Float", collection: "Milk", rarity: "uncommon", material: "frosted", sound: "poppy", size: "1.25U", profile: "XDA", color: "#f7efe9", accent: "#c9b4a8", legend: "Again", icon: "◒", description: "Creamy translucent cap with a brighter bounce.", unlockCondition: "3 total presses", unlockPresses: 3 },
  { id: "kcap-matcha-1", name: "Matcha Core", collection: "Matcha", rarity: "common", material: "ABS", sound: "thock", size: "1U", profile: "Cherry", color: "#d7e1c0", accent: "#7c8b5b", legend: "Calm", icon: "✦", description: "Muted green with a dense mechanical response.", unlockCondition: "Starter cap", unlockPresses: 0 },
  { id: "kcap-matcha-2", name: "Matcha Beam", collection: "Matcha", rarity: "rare", material: "translucent", sound: "marble", size: "1.5U", profile: "SA", color: "#cfe1b1", accent: "#8ba86b", legend: "Glow", icon: "◍", description: "Semi-clear shell with a gentle luminous edge.", unlockCondition: "12 presses on Milk One", unlockPresses: 12 },
  { id: "kcap-sakura-1", name: "Sakura Drift", collection: "Sakura", rarity: "common", material: "PBT", sound: "creamy", size: "1U", profile: "DSA", color: "#efd9df", accent: "#c88ea4", legend: "Bloom", icon: "✿", description: "Dusty pink with a polished artisan finish.", unlockCondition: "Starter cap", unlockPresses: 0 },
  { id: "kcap-retro-1", name: "Retro Terminal", collection: "Retro Terminal", rarity: "uncommon", material: "ABS", sound: "clack", size: "1U", profile: "Cherry", color: "#cfd2c5", accent: "#525c4d", legend: "Run", icon: "⌘", description: "Industrial grey with a sharp old-machine feel.", unlockCondition: "Starter cap", unlockPresses: 0 },
  { id: "kcap-midnight-1", name: "Midnight Arc", collection: "Midnight", rarity: "epic", material: "metallic", sound: "thock", size: "1.25U", profile: "SA", color: "#1c2230", accent: "#6172a4", legend: "Night", icon: "◈", description: "Deep blue-black with a cold reflective highlight.", unlockCondition: "250 total presses", unlockPresses: 250 },
  { id: "kcap-jelly-1", name: "Jelly Orbit", collection: "Jelly", rarity: "rare", material: "clear resin", sound: "marble", size: "1.5U", profile: "XDA", color: "#d8eef0", accent: "#7fb6bc", legend: "Tap", icon: "◌", description: "Clear body with a candy-like colored core.", unlockCondition: "36 presses on Milk One", unlockPresses: 36 },
  { id: "kcap-cyber-1", name: "Cyber Pulse", collection: "Cyber", rarity: "legendary", material: "glossy artisan", sound: "clack", size: "2U", profile: "SA", color: "#1e1730", accent: "#b35cff", legend: "Grid", icon: "⬡", description: "High contrast purple glow with a collectible silhouette.", unlockCondition: "Rewards milestone", unlockPresses: 14_800 },
  { id: "kcap-stone-1", name: "Stone Plane", collection: "Stone", rarity: "uncommon", material: "ceramic-like", sound: "silent", size: "1.25U", profile: "DSA", color: "#d7d1c7", accent: "#8b8177", legend: "Calm", icon: "◫", description: "Heavy matte surface that reads like polished stone.", unlockCondition: "144 total presses", unlockPresses: 144 },
  { id: "kcap-cloud-1", name: "Cloud Drift", collection: "Cloud", rarity: "common", material: "frosted", sound: "silent", size: "1U", profile: "XDA", color: "#e9eef3", accent: "#9ca9b8", legend: "Soft", icon: "☁", description: "Airy pale top with a low-contrast translucent shell.", unlockCondition: "60 total presses", unlockPresses: 60 },
  { id: "kcap-arcade-1", name: "Arcade Neon", collection: "Arcade", rarity: "epic", material: "translucent", sound: "poppy", size: "1.5U", profile: "DSA", color: "#fedf88", accent: "#ff7c66", legend: "Play", icon: "◉", description: "Bright, playful, and loud in the best possible way.", unlockCondition: "4,200 eligible presses", unlockPresses: 4_200 },
  { id: "kcap-transparent-1", name: "Clear Window", collection: "Transparent", rarity: "legendary", material: "clear resin", sound: "tactile", size: "1.5U", profile: "XDA", color: "#e6f3f6", accent: "#7fa6b2", legend: "See", icon: "◇", description: "A clear-cast shell with a suspended legend plane.", unlockCondition: "8,000 eligible presses", unlockPresses: 8_000 },
  { id: "kcap-artist-1", name: "Atelier Rune", collection: "Limited Artist Series", rarity: "legendary", material: "glossy artisan", sound: "custom", size: "2U", profile: "SA", color: "#28272d", accent: "#d9b97d", legend: "Rune", icon: "✦", description: "A numbered showpiece with a hand-finished museum silhouette.", unlockCondition: "Physical reward milestone", unlockPresses: 14_800 },
] as const satisfies readonly KeycapDefinition[];
