import type { WebCandidate } from "./web-candidates";
import type { ProductDiscoveryCandidate } from "./discovery-types";

export function toWebCandidate(candidate: ProductDiscoveryCandidate): WebCandidate {
  return {
    id: candidate.id,
    title: candidate.title,
    merchant: candidate.merchant,
    provider: candidate.provider,
    sourceType: candidate.sourceType,
    brand: candidate.brand,
    productName: candidate.title,
    category: candidate.category,
    color: candidate.color,
    price: candidate.price,
    retailer: candidate.merchant,
    url: candidate.url,
    detailUrl: candidate.productDetailUrl,
    discoveryUrl: candidate.searchUrl,
    detailPageVerified: candidate.detailPageVerified,
    purchaseEligible: candidate.purchaseEligible,
    matchState: candidate.matchState,
    imageUrls: candidate.imageUrls,
    source: `discovery:${candidate.provider}`,
    sourceUrl: candidate.productDetailUrl ?? candidate.searchUrl ?? undefined,
    pageTrust: candidate.sourceConfidence ?? 0.5,
    productDetailUrl: candidate.productDetailUrl,
    searchUrl: candidate.searchUrl,
    canonicalClass: candidate.canonicalClass,
    modelName: candidate.modelName,
    sourceConfidence: candidate.sourceConfidence,
    primaryImageUrl: candidate.primaryImageUrl,
    imageAvailable: candidate.imageAvailable,
    identifiers: candidate.identifiers,
    modelCode: candidate.modelCode,
    sku: candidate.sku,
    gtin: candidate.gtin,
    ean: candidate.ean,
    upc: candidate.upc,
    sourceProviders: candidate.sourceProviders,
    sourceAgreementCount: candidate.sourceAgreementCount,
    sources: candidate.sources,
    rawMetadata: candidate.rawMetadata,
  };
}
