import { z } from "zod";
import { IDENTIFIER_KINDS } from "../commerce/types";

const webCandidateSchema = z.object({
  id: z.string(),
  brand: z.string().nullable(),
  productName: z.string(),
  category: z.string().nullable(),
  color: z.string().nullable(),
  price: z.object({ value: z.number().nullable(), currency: z.string().nullable() }),
  retailer: z.string(),
  url: z.url(),
  imageUrls: z.array(z.url()),
  availability: z.string().optional(),
  source: z.string(),
  sourceUrl: z.url().optional(),
  pageTrust: z.number().min(0).max(1).optional(),
  visualScore: z.number().min(0).max(1).optional(),
  visualSource: z.string().optional(),
  sameProductProbability: z.number().min(0).max(1).optional(),
  visualEvidence: z.array(z.string()).optional(),
  visualConflicts: z.array(z.string()).optional(),
  detailUrl: z.url().nullable().optional(),
  discoveryUrl: z.url().nullable().optional(),
  detailPageVerified: z.boolean().optional(),
  purchaseEligible: z.boolean().optional(),
  matchState: z.enum(["exact", "likely", "similar", "review", "unverified"]).optional(),
  catalogProductId: z.string().optional(),
  affiliate: z.boolean().optional(),
  commissionRate: z.number().nullable().optional(),
  productDetailUrl: z.url().nullable().optional(),
  searchUrl: z.url().nullable().optional(),
  title: z.string().optional(),
  merchant: z.string().optional(),
  provider: z.string().optional(),
  sourceType: z.string().optional(),
  canonicalClass: z.string().nullable().optional(),
  modelName: z.string().nullable().optional(),
  sourceConfidence: z.number().nullable().optional(),
  imageAvailable: z.boolean().optional(),
  identifiers: z.array(z.object({ kind: z.enum(IDENTIFIER_KINDS), value: z.string() })).optional(),
  modelCode: z.string().nullable().optional(),
  sku: z.string().nullable().optional(),
  gtin: z.string().nullable().optional(),
  ean: z.string().nullable().optional(),
  upc: z.string().nullable().optional(),
  sourceProviders: z.array(z.string()).optional(),
  sourceAgreementCount: z.number().int().nonnegative().optional(),
  sources: z.array(z.record(z.string(), z.unknown())).optional(),
  rawMetadata: z.record(z.string(), z.unknown()).optional(),
  visualSiglipScore: z.number().min(0).max(1).nullable().optional(),
  preliminaryIdentityScore: z.number().min(0).max(1).nullable().optional(),
  finalIdentityScore: z.number().min(0).max(1).nullable().optional(),
  identityStatus: z.enum(["VERIFIED", "LIKELY", "POSSIBLE", "CONFLICT", "UNVERIFIED"]).optional(),
  variantExactness: z.boolean().optional(),
  matchReasons: z.array(z.string()).optional(),
  conflicts: z.array(z.string()).optional(),
  visualEvidenceDetail: z.object({
    model: z.string(),
    score: z.number().min(0).max(1),
    queryCropMode: z.enum(["polygon", "bbox"]),
    candidateImageAvailable: z.boolean(),
  }).optional(),
});

export const webResponseSchema = z.object({ candidates: z.array(webCandidateSchema) });
