import sys

file_path = r"c:\Users\임현수\Downloads\STS\STS-claude-visual-commerce-prd-m2xfdo\lib\real-products-data.ts"

new_content = '''export interface RealProduct {
  id: string;
  brand: string;
  name: string;
  category: "스킨케어" | "선케어" | "메이크업" | "클렌징" | "디바이스";
  originalPrice: number;
  salePrice: number;
  discountRate: number;
  image: string;
  rankBadge: string;
  collabType: "마켓" | "공유리워드" | "무료협찬" | "광고";
  rewardRate: string;
  status: "신청 가능" | "협업 중" | "마감 임박";
  retailer: string;
  purchaseUrl: string;
  features: string[];
  description: string;
}

export const REAL_KBEAUTY_BESTSELLERS: RealProduct[] = [
  {
    id: "kb-romand-tint",
    brand: "rom&nd (롬앤)",
    name: "쥬시 래스팅 틴트 #25 베어 그레이프",
    category: "메이크업",
    originalPrice: 13000,
    salePrice: 8900,
    discountRate: 32,
    image: "/products/kb-romand-tint.jpg",
    rankBadge: "올리브영 어워즈 립 1위",
    collabType: "공유리워드",
    rewardRate: "리워드 15%",
    status: "신청 가능",
    retailer: "올리브영 · 지그재그",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=롬앤+쥬시래스팅틴트+베어그레이프",
    features: ["쿨톤 인생 베이스 립", "맑고 투명한 탕후루 광택", "오랜 시간 지속되는 착색력"],
    description: "바르는 순간 투명한 탕후루 광택이 차오르는 쿨톤 베스트 컬러. 자연스러운 쿨 누디 포도빛.",
  },
  {
    id: "kb-toocool-shading",
    brand: "too cool for school (투쿨포스쿨)",
    name: "아트클래스 바이로댕 쉐딩 마스터 [전용 브러쉬 증정]",
    category: "메이크업",
    originalPrice: 16000,
    salePrice: 11200,
    discountRate: 30,
    image: "/products/kb-toocool-shading.jpg",
    rankBadge: "국민 콧대 쉐딩 1위",
    collabType: "마켓",
    rewardRate: "커미션 14%",
    status: "신청 가능",
    retailer: "올리브영 · 지그재그",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=투쿨포스쿨+아트클래스+바이로댕+쉐딩",
    features: ["동양인 피부 맞춤 3색 그라데이션", "자연스러운 콧대 입체 윤곽", "가루 날림 없는 밀착 텍스처"],
    description: "대한민국 1등 국민 쉐딩. 붉은기 없이 자연스러운 음영으로 오뚝한 콧대와 슬림한 V라인 연출.",
  },
  {
    id: "kb-clio-liner",
    brand: "CLIO (클리오)",
    name: "워터프루프 펜라이너 킬브라운 #02 브라운",
    category: "메이크업",
    originalPrice: 18000,
    salePrice: 12600,
    discountRate: 30,
    image: "/products/kb-clio-liner.jpg",
    rankBadge: "올리브영 아이라이너 1위",
    collabType: "공유리워드",
    rewardRate: "리워드 13%",
    status: "신청 가능",
    retailer: "올리브영 공식몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=클리오+워터프루프+펜라이너+킬브라운",
    features: ["초극세 마이크로 브러쉬", "유수분에 지워지지 않는 롱래스팅", "선명하고 자연스러운 딥 브라운"],
    description: "한 번의 터치로 눈꼬리까지 번짐 없이 정교하게 그려지는 국민 워터프루프 아이라이너.",
  },
  {
    id: "kb-etude-brow",
    brand: "ETUDE (에뛰드)",
    name: "드로잉 아이브로우 슬림 0.05mm #01 다크브라운",
    category: "메이크업",
    originalPrice: 5000,
    salePrice: 3500,
    discountRate: 30,
    image: "/products/kb-etude-brow.jpg",
    rankBadge: "국민 아이브로우 1위",
    collabType: "마켓",
    rewardRate: "커미션 12%",
    status: "신청 가능",
    retailer: "올리브영 · 에뛰드몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=에뛰드+드로잉+아이브로우",
    features: ["뭉침 없는 하드 포뮬러", "한 올 한 올 심은 듯한 눈썹결", "자연스러운 농도 조절 스크류 내장"],
    description: "눈썹 숱 없는 부위도 한 올 한 올 진짜 내 털처럼 결을 살려주는 극세사 아이브로우 펜슬.",
  },
  {
    id: "kb-3ce-blush",
    brand: "3CE (쓰리씨이)",
    name: "무드 레시피 페이스 블러쉬 #MONO PINK",
    category: "메이크업",
    originalPrice: 18000,
    salePrice: 13500,
    discountRate: 25,
    image: "/products/kb-3ce-blush.jpg",
    rankBadge: "올리브영 블러셔 1위",
    collabType: "광고",
    rewardRate: "광고비 120만원",
    status: "신청 가능",
    retailer: "올리브영 · 스타일난다",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=3CE+무드레시피+페이스블러쉬+모노핑크",
    features: ["모공 블러링 파우더", "맑고 투명한 수채화 수줍은 핑크", "오랜 시간 다크닝 없는 화사함"],
    description: "볼 위에 맑고 은은하게 번지는 수채화 발색. 피부 요철을 매끈하게 지워주는 블러 효과 블러셔.",
  },
  {
    id: "kb-glint-highlighter",
    brand: "Glint (글린트)",
    name: "하이라이터 #01 듀이 문 (Dewy Moon)",
    category: "메이크업",
    originalPrice: 22000,
    salePrice: 15400,
    discountRate: 30,
    image: "/products/kb-glint-highlighter.jpg",
    rankBadge: "SNS 대란 속광 하이라이터",
    collabType: "공유리워드",
    rewardRate: "리워드 15%",
    status: "신청 가능",
    retailer: "올리브영 공식몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=글린트+하이라이터+듀이문",
    features: ["베이크드 제형 텁텁함 제로", "햇살 머금은 듯한 맑은 샴페인 골드", "코끝 & 광대 입체 광채"],
    description: "스치기만 해도 피부 본연의 투명한 속광을 켜주는 프리미엄 펄 하이라이터.",
  },
  {
    id: "kb-clio-cushion",
    brand: "CLIO (클리오)",
    name: "킬커버 더 뉴 파운웨어 쿠션 [본품+리필 기획세트]",
    category: "메이크업",
    originalPrice: 36000,
    salePrice: 25200,
    discountRate: 30,
    image: "/products/kb-clio-cushion.jpg",
    rankBadge: "올리브영 단독기획 베스트",
    collabType: "광고",
    rewardRate: "광고비 150만원",
    status: "신청 가능",
    retailer: "올리브영 공식몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=클리오+킬커버+더뉴파운웨어쿠션",
    features: ["72시간 무너짐 없는 밀착 커버", "초슬림 파우더 입자", "세미매트 피니시"],
    description: "더 얇고 더 섬세해진 킬커버. 가볍게 얹히면서도 결점을 감쪽같이 커버하는 올리브영 1위 쿠션.",
  },
  {
    id: "kb-dalba-serum",
    brand: "d'Alba (달바)",
    name: "화이트 트러플 퍼스트 스프레이 세럼 100ml",
    category: "스킨케어",
    originalPrice: 29900,
    salePrice: 19900,
    discountRate: 33,
    image: "/products/kb-dalba-serum.jpg",
    rankBadge: "올리브영 1위 승무원미스트",
    collabType: "무료협찬",
    rewardRate: "본품 무상 + 10%",
    status: "신청 가능",
    retailer: "올리브영 · 네이버",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=달바+화이트+트러플+퍼스트+스프레이+세럼",
    features: ["이탈리아 화이트 트러플 함유", "오일층+세럼층 듀얼 광채", "안개 분사 저자극 비건"],
    description: "승무원 미스트로 유명한 프리미엄 비건 항산화 세럼. 흔들어서 쓱 뿌리면 즉각적인 수분 광채를 선사합니다.",
  },
  {
    id: "kb-boj-sun",
    brand: "Beauty of Joseon (조선미녀)",
    name: "맑은쌀선크림 SPF50+ PA++++ 50ml",
    category: "선케어",
    originalPrice: 18000,
    salePrice: 13500,
    discountRate: 25,
    image: "/products/kb-boj-sun.jpg",
    rankBadge: "글로벌 No.1 선크림",
    collabType: "마켓",
    rewardRate: "커미션 15%",
    status: "신청 가능",
    retailer: "공식몰 · 올리브영",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=조선미녀+맑은쌀선크림",
    features: ["백탁 없는 촉촉한 유기자차", "쌀추출물 30% 함유", "글로벌 틱톡 누적 1,000만병 돌파"],
    description: "전 세계를 뒤흔든 K-뷰티 대표 선크림. 로션처럼 산뜻하고 촉촉하게 스며드는 수분 밀착 텍스처.",
  },
  {
    id: "kb-roundlab-cream",
    brand: "ROUND LAB (라운드랩)",
    name: "자작나무 수분 크림 80ml",
    category: "스킨케어",
    originalPrice: 32000,
    salePrice: 22400,
    discountRate: 30,
    image: "/products/kb-roundlab-cream.jpg",
    rankBadge: "화해 뷰티어워드 수분크림 1위",
    collabType: "마켓",
    rewardRate: "커미션 14%",
    status: "신청 가능",
    retailer: "올리브영 · 공식몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=라운드랩+자작나무+수분크림",
    features: ["인제 자작나무 수액 듬뿍", "비타히알루론산 48시간 보습", "끈적임 0% 수분 캡슐"],
    description: "메마른 피부에 맑은 수분을 급속 충전하는 청량한 젤 크림.",
  },
  {
    id: "kb-manyo-oil",
    brand: "ma:nyo (마녀공장)",
    name: "퓨어 클렌징 오일 200ml",
    category: "클렌징",
    originalPrice: 29000,
    salePrice: 18900,
    discountRate: 35,
    image: "/products/kb-manyo-oil.jpg",
    rankBadge: "누적 판매 1,000만병 돌파",
    collabType: "공유리워드",
    rewardRate: "리워드 12%",
    status: "신청 가능",
    retailer: "올리브영 · 공식몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=마녀공장+퓨어+클렌징+오일",
    features: ["블랙헤드 피지 99.7% 세정", "14가지 식물성 영양 오일", "모공을 막지 않는 친수성 에멀전"],
    description: "물과 닿는 순간 우윳빛으로 유화되며 모공 속 노폐물을 말끔히 녹여내는 국민 클렌징 오일.",
  },
  {
    id: "kb-anua-toner",
    brand: "Anua (아누아)",
    name: "어성초 77% 수딩 토너 250ml",
    category: "스킨케어",
    originalPrice: 23000,
    salePrice: 16100,
    discountRate: 30,
    image: "/products/kb-anua-toner.jpg",
    rankBadge: "올리브영 진정토너 1위",
    collabType: "마켓",
    rewardRate: "커미션 13%",
    status: "신청 가능",
    retailer: "올리브영 · 무신사뷰티",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=아누아+어성초+77+수딩+토너",
    features: ["국내산 어성초 추출물 77%", "민감 여드름성 피부 적합 테스트", "붉은기 즉각 진정"],
    description: "트러블과 열감으로 예민해진 피부를 빠르게 잠재우는 저자극 진정 토너.",
  },
  {
    id: "kb-torriden-serum",
    brand: "Torriden (토리든)",
    name: "다이브인 저분자 히알루론산 세럼 50ml",
    category: "스킨케어",
    originalPrice: 22000,
    salePrice: 15400,
    discountRate: 30,
    image: "/products/kb-torriden-serum.jpg",
    rankBadge: "화해 에센스/세럼 3년 연속 1위",
    collabType: "무료협찬",
    rewardRate: "본품 무상 + 12%",
    status: "신청 가능",
    retailer: "올리브영 공식몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=토리든+다이브인+저분자+히알루론산+세럼",
    features: ["5D 복합 저분자 히알루론산", "속당김 완벽 해결", "산뜻하고 촉촉한 워터 세럼"],
    description: "피부 깊은 곳까지 차오르는 5중 히알루론산의 청량한 수분 폭탄.",
  },
  {
    id: "kb-medicube-pro",
    brand: "medicube (메디큐브)",
    name: "에이지알 부스터 프로 (홈케어 6 in 1)",
    category: "디바이스",
    originalPrice: 399000,
    salePrice: 299000,
    discountRate: 25,
    image: "/products/kb-medicube-pro.jpg",
    rankBadge: "글로벌 100만대 판매 뷰티 디바이스",
    collabType: "광고",
    rewardRate: "건당 350만원",
    status: "협업 중",
    retailer: "메디큐브 공식몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=메디큐브+에이지알+부스터+프로",
    features: ["전기자극 모공/탄력/광채 케어", "스마트 모바일 앱 연동", "미국 FDA 등록 안전 인증"],
    description: "에스테틱 관리를 집에서 그대로 재현하는 최첨단 6-in-1 토탈 케어 뷰티 디바이스.",
  },
  {
    id: "kb-aestura-cream",
    brand: "AESTURA (에스트라)",
    name: "아토베리어365 크림 80ml",
    category: "스킨케어",
    originalPrice: 33000,
    salePrice: 26400,
    discountRate: 20,
    image: "/products/kb-aestura-cream.jpg",
    rankBadge: "피부과 처방 1위 장벽크림",
    collabType: "공유리워드",
    rewardRate: "리워드 12%",
    status: "신청 가능",
    retailer: "올리브영 · 아모레몰",
    purchaseUrl: "https://search.shopping.naver.com/search/all?query=에스트라+아토베리어365+크림",
    features: ["고밀도 더마온 세라마이드 캡슐", "120시간 장벽 보습 유지", "민감 피부 더마 테스트 완료"],
    description: "피부 장벽이 무너졌을 때 찾는 SOS 보습제. 미세 캡슐이 부드럽게 녹으며 피부 틈새를 촘촘히 메워줍니다.",
  }
];

export interface BrandLogo {
  id: string;
  name: string;
  svg: string;
}

export const REAL_BRAND_LOGOS: BrandLogo[] = [
  { id: "dasique", name: "dasique (데이지크)", svg: "/brands/logo-10.svg" },
  { id: "melixir", name: "melixir (멜릭서)", svg: "/brands/logo-35.svg" },
  { id: "vivelab", name: "ViveLab (바이브랩)", svg: "/brands/logo-32.svg" },
  { id: "refilled", name: "Refilled (리필드)", svg: "/brands/logo-17.svg" },
  { id: "citybreeze", name: "CITYBREEZE", svg: "/brands/logo-05.svg" },
  { id: "urago", name: "URAGO", svg: "/brands/logo-01.svg" },
  { id: "rel", name: "RE_L", svg: "/brands/logo-77.svg" },
  { id: "teazen", name: "TEAZEN (티젠)", svg: "/brands/logo-12.svg" },
  { id: "monochrome", name: "MONOCHROME", svg: "/brands/logo-03.svg" },
  { id: "lukt", name: "lukt (룩트)", svg: "/brands/logo-29.svg" },
  { id: "cos", name: "COS (코스)", svg: "/brands/logo-26.svg" },
  { id: "hdex", name: "HDEX (에이치덱스)", svg: "/brands/logo-16.svg" },
  { id: "notia", name: "NOTIA (노티아)", svg: "/brands/logo-11.svg" },
  { id: "mongdol", name: "MONGDOL (몽돌)", svg: "/brands/logo-49.svg" },
  { id: "rememberjane", name: "REMEMBER JANE", svg: "/brands/logo-31.svg" },
  { id: "dubleve", name: "DUBLEVE", svg: "/brands/logo-04.svg" },
  { id: "knola", name: "Knola", svg: "/brands/logo-06.svg" },
  { id: "brabantia", name: "brabantia", svg: "/brands/logo-15.svg" },
  { id: "childlife", name: "ChildLife", svg: "/brands/logo-28.svg" },
  { id: "propermarket", name: "Proper Market", svg: "/brands/logo-20.svg" },
  { id: "todo", name: "TŌDO", svg: "/brands/logo-21.svg" },
  { id: "inertia", name: "INERTIA", svg: "/brands/logo-22.svg" },
  { id: "sartu", name: "SARTU", svg: "/brands/logo-23.svg" },
  { id: "tilli-die", name: "TILL I DIE", svg: "/brands/logo-24.svg" },
];

export interface FaceSegmentationZone {
  id: string;
  zone: "lips" | "nose" | "eyes" | "eyebrows" | "cheeks" | "tzone" | "barrier" | "contour";
  zoneName: string; // "입술 (Lips)" | "코 / 콧대 (Nose)" | "눈 / 아이 (Eyes)" | "눈썹 (Eyebrows)" | "볼 / 치크 (Cheeks)"
  zoneIcon: string;
  confidence: number; // e.g. 99.8
  polygonPoints: string; // SVG polygon coords (viewBox 0 0 100 100)
  fillColor: string;
  strokeColor: string;
  glowColor: string;
  anchorX: number; // %
  anchorY: number; // %
  productId: string;
  brand: string;
  productName: string;
  price: number;
  discount: number;
  productImage: string;
  cosmeticRole: string; // "탕후루 광택 립 발색" | "콧대 음영 입체감" | "선명한 딥브라운 눈매" | "한올한올 결 아이브로우" | "수채화 블러링 생기"
  appliedEffect: string; // "쿨 누디 베어그레이프 2콧 레이어링" | "바이로댕 쉐딩 2번 믹스 콧대 터치"
  textureNote: string; // "유리알 광택막 코팅" | "뭉침 없는 미세 음영 파우더"
}

export interface KBeautyCreatorPost {
  id: string;
  creatorHandle: string;
  creatorName: string;
  creatorAvatar: string;
  modelImage: string;
  routineTitle: string;
  caption: string;
  likes: number;
  videoUrl?: string;
  productTags: {
    productId: string;
    brand: string;
    productName: string;
    price: number;
    discount: number;
    tagX: number;
    tagY: number;
    productImage: string;
  }[];
  faceZones: FaceSegmentationZone[];
}

export const KBEAUTY_CREATOR_POSTS: KBeautyCreatorPost[] = [
  {
    id: "post-kb-01",
    creatorHandle: "yoon.glow",
    creatorName: "윤글로우",
    creatorAvatar: "/kbeauty-models/kb-creator-01.jpg",
    modelImage: "/kbeauty-models/kb-creator-01.jpg",
    routineTitle: "오뚝한 입체 윤곽 & 탕후루 글로우 립 튜토리얼 ✨",
    caption: "콧대 쉐딩과 맑은 립 하나로 이목구비가 확 살아나요. 롬앤 베어그레이프 틴트 + 투쿨 바이로댕 쉐딩 + 클리오 라이너 조합 추천!",
    likes: 24800,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-fashion-model-in-neon-city-lights-41315-large.mp4",
    productTags: [
      {
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트 #25 베어 그레이프",
        price: 8900,
        discount: 32,
        tagX: 50,
        tagY: 64,
        productImage: "/products/kb-romand-tint.jpg"
      },
      {
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        tagX: 47,
        tagY: 53,
        productImage: "/products/kb-toocool-shading.jpg"
      },
      {
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        tagX: 36,
        tagY: 42,
        productImage: "/products/kb-clio-liner.jpg"
      },
      {
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림 0.05mm",
        price: 3500,
        discount: 30,
        tagX: 35,
        tagY: 35,
        productImage: "/products/kb-etude-brow.jpg"
      },
      {
        productId: "kb-3ce-blush",
        brand: "3CE",
        productName: "무드 레시피 페이스 블러쉬 #모노핑크",
        price: 13500,
        discount: 25,
        tagX: 33,
        tagY: 53,
        productImage: "/products/kb-3ce-blush.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-01-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.8,
        polygonPoints: "44,61.5 47,59.8 50,60.5 53,59.8 56,61.5 58,63.2 55,66.4 50,68 45,66.4 42,63.2",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 64,
        productId: "kb-romand-tint",
        brand: "rom&nd (롬앤)",
        productName: "쥬시 래스팅 틴트 #25 베어 그레이프",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "글래스 탕후루 광택 립 발색",
        appliedEffect: "쿨 누디 베어그레이프 2회 레이어링 도포",
        textureNote: "맑은 수분 코팅막으로 입술 볼륨감 극대화"
      },
      {
        id: "zone-kb-01-nose",
        zone: "nose",
        zoneName: "코 / 콧대 (Nose)",
        zoneIcon: "👃",
        confidence: 99.6,
        polygonPoints: "47,43 51,43 52,48 53,54 55,57 51,59 47,57 45,54 46,48",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 49,
        anchorY: 53,
        productId: "kb-toocool-shading",
        brand: "too cool for school (투쿨포스쿨)",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        productImage: "/products/kb-toocool-shading.jpg",
        cosmeticRole: "슬림 콧대 음영 & 코끝 입체 하이라이팅",
        appliedEffect: "중간 음영 컬러로 미간부터 콧망울까지 섬세 터치",
        textureNote: "붉은기 제로 미세 파우더 입자로 자연스러운 그림자 연출"
      },
      {
        id: "zone-kb-01-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.7,
        polygonPoints: "28,42 35,39 42,42 39,46 32,46",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 35,
        anchorY: 42,
        productId: "kb-clio-liner",
        brand: "CLIO (클리오)",
        productName: "워터프루프 펜라이너 킬브라운 #02 브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "또렷한 눈꼬리 슬림 아이라인",
        appliedEffect: "눈꼬리 라인을 15도 슬림하게 연장하여 트임 효과 연출",
        textureNote: "0.01mm 극세 팁으로 번짐 없는 초밀착 워터프루프 라인"
      },
      {
        id: "zone-kb-01-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.4,
        polygonPoints: "26,34 33,31 42,33 41,36 33,34 26,36",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 34,
        anchorY: 33,
        productId: "kb-etude-brow",
        brand: "ETUDE (에뛰드)",
        productName: "드로잉 아이브로우 슬림 0.05mm",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "한 올 한 올 입체 눈썹결 드로잉",
        appliedEffect: "눈썹 앞머리 결을 세우고 꼬리를 날렵하게 정돈",
        textureNote: "하드 포뮬러 파우더로 뭉침 없는 자연스러운 결 표현"
      },
      {
        id: "zone-kb-01-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 치크 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.5,
        polygonPoints: "26,48 34,44 42,48 43,56 38,63 29,61 24,54",
        fillColor: "rgba(236, 72, 153, 0.35)",
        strokeColor: "rgba(244, 114, 182, 0.95)",
        glowColor: "rgba(236, 72, 153, 0.8)",
        anchorX: 33,
        anchorY: 53,
        productId: "kb-3ce-blush",
        brand: "3CE (쓰리씨이)",
        productName: "무드 레시피 페이스 블러쉬 #모노핑크",
        price: 13500,
        discount: 25,
        productImage: "/products/kb-3ce-blush.jpg",
        cosmeticRole: "수채화 수줍은 핑크 생기 & 모공 블러링",
        appliedEffect: "앞볼 중앙부터 관자놀이 방향으로 사선 블렌딩",
        textureNote: "피부 요철을 매끄럽게 메우는 고운 블러 파우더"
      }
    ]
  },
  {
    id: "post-kb-02",
    creatorHandle: "minji.makeup",
    creatorName: "민지메이크업",
    creatorAvatar: "/kbeauty-models/kb-creator-02.jpg",
    modelImage: "/kbeauty-models/kb-creator-02.jpg",
    routineTitle: "청담동 샵 72시간 지속 도자기 세미매트 & 쿨톤 아이 룩",
    caption: "트러블 자국 모공까지 싹 가려주는 클리오 킬커버 쿠션과 선명한 클리오 라이너의 완벽 조합.",
    likes: 31200,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-light-1232-large.mp4",
    productTags: [
      {
        productId: "kb-clio-cushion",
        brand: "CLIO",
        productName: "킬커버 더 뉴 파운웨어 쿠션",
        price: 25200,
        discount: 30,
        tagX: 52,
        tagY: 48,
        productImage: "/products/kb-clio-cushion.jpg"
      },
      {
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        tagX: 38,
        tagY: 40,
        productImage: "/products/kb-clio-liner.jpg"
      },
      {
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        tagX: 50,
        tagY: 52,
        productImage: "/products/kb-toocool-shading.jpg"
      },
      {
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트 #25 베어그레이프",
        price: 8900,
        discount: 32,
        tagX: 50,
        tagY: 66,
        productImage: "/products/kb-romand-tint.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-02-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.7,
        polygonPoints: "44,63 47,61.5 50,62 53,61.5 56,63 58,65 54,68 50,69 46,68 42,65",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 65,
        productId: "kb-romand-tint",
        brand: "rom&nd (롬앤)",
        productName: "쥬시 래스팅 틴트 #25 베어 그레이프",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "누디 모브 립 그라데이션",
        appliedEffect: "입술 안쪽부터 스머징하여 자연스러운 오버립 연출",
        textureNote: "탕후루 수분 코팅막으로 매끈한 입술 주름 커버"
      },
      {
        id: "zone-kb-02-nose",
        zone: "nose",
        zoneName: "코 / 콧대 (Nose)",
        zoneIcon: "👃",
        confidence: 99.5,
        polygonPoints: "48,43 52,43 53,49 54,54 56,58 52,60 48,58 46,54 47,49",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 50,
        anchorY: 53,
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        productImage: "/products/kb-toocool-shading.jpg",
        cosmeticRole: "오뚝한 조각 콧대 쉐딩",
        appliedEffect: "콧대 라인 양옆 음영 & 코끝 V자 커팅 쉐딩",
        textureNote: "미세 블러 파우더 입자로 뭉침 없는 음영 완성"
      },
      {
        id: "zone-kb-02-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.8,
        polygonPoints: "31,40 38,37 45,40 42,44 35,44",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 38,
        anchorY: 40,
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운 #02 브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "또렷한 캐츠아이 라이너",
        appliedEffect: "점막부터 눈꼬리까지 번짐 없이 선명한 아이라인",
        textureNote: "지속력 72시간 번짐 없는 파워프루프"
      },
      {
        id: "zone-kb-02-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.6,
        polygonPoints: "28,32 37,29 46,31 45,34 37,32 28,34",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 37,
        anchorY: 31,
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림 0.05mm",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "세련된 아치형 브로우 라인",
        appliedEffect: "눈썹 산을 부드럽게 살린 모던 아치 디자인",
        textureNote: "하드 포뮬러 왁스로 눈썹 결 고정력 우수"
      },
      {
        id: "zone-kb-02-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 베이스 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.8,
        polygonPoints: "27,47 36,43 45,46 45,55 39,63 29,60 25,54",
        fillColor: "rgba(59, 130, 246, 0.35)",
        strokeColor: "rgba(96, 165, 250, 0.95)",
        glowColor: "rgba(59, 130, 246, 0.8)",
        anchorX: 35,
        anchorY: 52,
        productId: "kb-clio-cushion",
        brand: "CLIO (클리오)",
        productName: "킬커버 더 뉴 파운웨어 쿠션",
        price: 25200,
        discount: 30,
        productImage: "/products/kb-clio-cushion.jpg",
        cosmeticRole: "72시간 결점 제로 도자기 베이스",
        appliedEffect: "03 리넨 얇게 레이어링하여 모공 결점 완전 커버",
        textureNote: "세미매트 피니시로 마스크 묻어남 제로"
      }
    ]
  },
  {
    id: "post-kb-03",
    creatorHandle: "soyeon.skin",
    creatorName: "소연스킨케어",
    creatorAvatar: "/kbeauty-models/kb-creator-03.jpg",
    modelImage: "/kbeauty-models/kb-creator-03.jpg",
    routineTitle: "피부과 처방 SOS 장벽 보습 & 내추럴 윤곽 루틴 💧",
    caption: "환절기 뒤집어진 피부엔 에스트라 세라마이드 캡슐 크림 + 글린트 하이라이터로 건강한 윤기 부여.",
    likes: 18900,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-young-woman-applying-makeup-in-front-of-a-mirror-39824-large.mp4",
    productTags: [
      {
        productId: "kb-aestura-cream",
        brand: "AESTURA",
        productName: "아토베리어365 크림 80ml",
        price: 26400,
        discount: 20,
        tagX: 42,
        tagY: 55,
        productImage: "/products/kb-aestura-cream.jpg"
      },
      {
        productId: "kb-glint-highlighter",
        brand: "Glint",
        productName: "하이라이터 #01 듀이 문",
        price: 15400,
        discount: 30,
        tagX: 50,
        tagY: 53,
        productImage: "/products/kb-glint-highlighter.jpg"
      },
      {
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트",
        price: 8900,
        discount: 32,
        tagX: 50,
        tagY: 65,
        productImage: "/products/kb-romand-tint.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-03-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.6,
        polygonPoints: "43,62 47,60 50,61 53,60 57,62 57,64 54,67 50,68 46,67 43,64",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 64,
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트 #25 베어그레이프",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "생기 촉촉 물광 립",
        appliedEffect: "각질 잠재우는 수분 글로스 오버랩",
        textureNote: "입술 당김 없는 고보습 틴트막"
      },
      {
        id: "zone-kb-03-nose",
        zone: "nose",
        zoneName: "코 / 코끝 (Nose)",
        zoneIcon: "👃",
        confidence: 99.5,
        polygonPoints: "47,44 51,44 52,50 54,54 55,57 51,59 47,57 45,54 46,50",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 50,
        anchorY: 53,
        productId: "kb-glint-highlighter",
        brand: "Glint (글린트)",
        productName: "하이라이터 #01 듀이 문",
        price: 15400,
        discount: 30,
        productImage: "/products/kb-glint-highlighter.jpg",
        cosmeticRole: "코끝 맑은 햇살 하이라이팅",
        appliedEffect: "콧대 중앙과 코끝에 듀이문 광채 톡톡",
        textureNote: "텁텁함 없는 베이크드 제형의 투명한 샴페인 펄"
      },
      {
        id: "zone-kb-03-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.4,
        polygonPoints: "29,42 36,39 43,42 40,46 33,46",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 36,
        anchorY: 42,
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "자연스러운 음영 눈매",
        appliedEffect: "눈매를 따라 얇고 자연스럽게 드로잉",
        textureNote: "자극 없는 부드러운 스폰지 팁"
      },
      {
        id: "zone-kb-03-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.3,
        polygonPoints: "27,33 35,30 43,32 42,35 35,33 27,35",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 35,
        anchorY: 32,
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "부드러운 내추럴 결 눈썹",
        appliedEffect: "빈 곳만 톡톡 메워 본연의 눈썹 결 살림",
        textureNote: "자연스러운 그레이 브라운 블렌딩"
      },
      {
        id: "zone-kb-03-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 장벽 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.8,
        polygonPoints: "25,48 35,44 44,47 44,56 38,64 28,62 23,55",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 34,
        anchorY: 53,
        productId: "kb-aestura-cream",
        brand: "AESTURA (에스트라)",
        productName: "아토베리어365 크림 80ml",
        price: 26400,
        discount: 20,
        productImage: "/products/kb-aestura-cream.jpg",
        cosmeticRole: "120시간 장벽 밀착 & 속보습 충전",
        appliedEffect: "세라마이드 캡슐을 체온으로 녹여 양 볼에 도포",
        textureNote: "끈적임 없이 피부 결을 채우는 고밀도 장벽 텍스처"
      }
    ]
  },
  {
    id: "post-kb-04",
    creatorHandle: "chaewon.daily",
    creatorName: "채원데일리",
    creatorAvatar: "/kbeauty-models/kb-creator-04.jpg",
    modelImage: "/kbeauty-models/kb-creator-04.jpg",
    routineTitle: "속당김 0% 수분 폭탄 워터풀 데일리 메이크업 🫧",
    caption: "토리든 저분자 세럼 듬뿍 흡수시키고 3CE 모노핑크 블러셔로 맑은 생기를 얹어주는 루틴.",
    likes: 21500,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-young-woman-applying-mascara-in-front-of-a-mirror-39825-large.mp4",
    productTags: [
      {
        productId: "kb-torriden-serum",
        brand: "Torriden",
        productName: "다이브인 저분자 히알루론산 세럼",
        price: 15400,
        discount: 30,
        tagX: 52,
        tagY: 48,
        productImage: "/products/kb-torriden-serum.jpg"
      },
      {
        productId: "kb-3ce-blush",
        brand: "3CE",
        productName: "무드 레시피 페이스 블러쉬",
        price: 13500,
        discount: 25,
        tagX: 34,
        tagY: 54,
        productImage: "/products/kb-3ce-blush.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-04-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.6,
        polygonPoints: "44,61 48,59 51,60 54,59 57,61 58,63 54,66 50,67 45,66 42,63",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 63,
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "촉촉한 수분 광택 립",
        appliedEffect: "얇게 2회 레이어링하여 자연스러운 광택 표현",
        textureNote: "맑은 탕후루 유리알 코팅"
      },
      {
        id: "zone-kb-04-nose",
        zone: "nose",
        zoneName: "코 / 콧대 (Nose)",
        zoneIcon: "👃",
        confidence: 99.4,
        polygonPoints: "47,44 51,44 53,50 54,54 55,57 51,59 47,57 45,54 46,50",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 49,
        anchorY: 53,
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        productImage: "/products/kb-toocool-shading.jpg",
        cosmeticRole: "자연스러운 데일리 콧대 음영",
        appliedEffect: "눈앞머리부터 자연스럽게 이어지는 코 윤곽",
        textureNote: "자연스러운 뉴트럴 브라운 피니시"
      },
      {
        id: "zone-kb-04-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.5,
        polygonPoints: "28,42 35,39 42,42 39,46 32,46",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 35,
        anchorY: 42,
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "순수하고 또렷한 강아지상 눈매",
        appliedEffect: "눈꼬리를 부드럽게 내려서 순한 인상 연출",
        textureNote: "극세 펜으로 섬세한 라인 연출"
      },
      {
        id: "zone-kb-04-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.4,
        polygonPoints: "26,33 34,30 42,32 41,35 34,33 26,35",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 34,
        anchorY: 32,
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "일자 동안 브로우",
        appliedEffect: "눈썹 모양을 곧게 잡아 어려보이는 효과",
        textureNote: "자연스러운 파우더 블렌딩"
      },
      {
        id: "zone-kb-04-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 치크 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.6,
        polygonPoints: "26,48 34,44 42,48 43,56 38,63 29,61 24,54",
        fillColor: "rgba(236, 72, 153, 0.35)",
        strokeColor: "rgba(244, 114, 182, 0.95)",
        glowColor: "rgba(236, 72, 153, 0.8)",
        anchorX: 33,
        anchorY: 53,
        productId: "kb-3ce-blush",
        brand: "3CE",
        productName: "무드 레시피 페이스 블러쉬",
        price: 13500,
        discount: 25,
        productImage: "/products/kb-3ce-blush.jpg",
        cosmeticRole: "생기 넘치는 피치 핑크 치크",
        appliedEffect: "애플존에 톡톡 두드려 맑은 혈색 부여",
        textureNote: "벨벳 파우더로 실키한 마무리"
      }
    ]
  },
  {
    id: "post-kb-05",
    creatorHandle: "haein.beauty",
    creatorName: "해인뷰티",
    creatorAvatar: "/kbeauty-models/kb-creator-05.jpg",
    modelImage: "/kbeauty-models/kb-creator-05.jpg",
    routineTitle: "성난 피부 10분 급속 진정 & 순한 베이스 메이크업 🌿",
    caption: "아누아 어성초 토너 패드로 붉은기 잡고 클리오 쿠션으로 얇게 피부톤 정돈.",
    likes: 27400,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-close-up-of-a-woman-applying-lipstick-39826-large.mp4",
    productTags: [
      {
        productId: "kb-anua-toner",
        brand: "Anua",
        productName: "어성초 77% 수딩 토너 250ml",
        price: 16100,
        discount: 30,
        tagX: 45,
        tagY: 50,
        productImage: "/products/kb-anua-toner.jpg"
      },
      {
        productId: "kb-clio-cushion",
        brand: "CLIO",
        productName: "킬커버 더 뉴 파운웨어 쿠션",
        price: 25200,
        discount: 30,
        tagX: 36,
        tagY: 52,
        productImage: "/products/kb-clio-cushion.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-05-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.7,
        polygonPoints: "44,62 47,60 50,61 53,60 56,62 58,64 54,67 50,68 46,67 42,64",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 64,
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "차분한 로즈 MLBB 립",
        appliedEffect: "자연스러운 혈색 위주의 톤다운 로즈 틴트 도포",
        textureNote: "수분 보습막 피니시"
      },
      {
        id: "zone-kb-05-nose",
        zone: "nose",
        zoneName: "코 / 콧대 (Nose)",
        zoneIcon: "👃",
        confidence: 99.5,
        polygonPoints: "47,44 51,44 53,50 54,54 55,57 51,59 47,57 45,54 46,50",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 50,
        anchorY: 53,
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        productImage: "/products/kb-toocool-shading.jpg",
        cosmeticRole: "코끝 쉐딩 & 블랙헤드 모공 블러링",
        appliedEffect: "콧망울을 둥글지 않게 날렵하게 잡아주는 쉐딩",
        textureNote: "파우더 코팅으로 번들거림 제로"
      },
      {
        id: "zone-kb-05-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.6,
        polygonPoints: "29,42 36,39 43,42 40,46 33,46",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 36,
        anchorY: 42,
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "단정한 세미 캣츠아이",
        appliedEffect: "눈매를 정갈하고 맑게 살려주는 얇은 브라운 라인",
        textureNote: "자극 없는 순한 워터프루프 포뮬러"
      },
      {
        id: "zone-kb-05-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.4,
        polygonPoints: "27,33 35,30 43,32 42,35 35,33 27,35",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 35,
        anchorY: 32,
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "단아한 일자 아치 브로우",
        appliedEffect: "인상을 부드럽게 만들어주는 흑갈색 결 표현",
        textureNote: "하드 포뮬러 지속력"
      },
      {
        id: "zone-kb-05-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 진정 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.8,
        polygonPoints: "26,48 35,44 44,47 44,56 38,64 28,62 23,55",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 34,
        anchorY: 53,
        productId: "kb-anua-toner",
        brand: "Anua (아누아)",
        productName: "어성초 77% 수딩 토너 250ml",
        price: 16100,
        discount: 30,
        productImage: "/products/kb-anua-toner.jpg",
        cosmeticRole: "홍조 붉은기 즉각 진정 & 수분 쿨링",
        appliedEffect: "화장솜에 적셔 양 볼에 5분간 토너팩 진행",
        textureNote: "약산성 무자극 진정 텍스처"
      }
    ]
  },
  {
    id: "post-kb-06",
    creatorHandle: "eunji.skin",
    creatorName: "은지스킨",
    creatorAvatar: "/kbeauty-models/kb-creator-06.jpg",
    modelImage: "/kbeauty-models/kb-creator-06.jpg",
    routineTitle: "피지 블랙헤드 제로 딥클렌징 & 모공 청정 케어 🫧",
    caption: "마녀공장 퓨어 클렌징 오일로 모공 속 굳은 피지 싹 녹여내고 글린트 하이라이터로 반짝이는 코끝 완성!",
    likes: 19800,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-young-woman-applying-lipstick-in-front-of-a-mirror-39827-large.mp4",
    productTags: [
      {
        productId: "kb-manyo-oil",
        brand: "ma:nyo",
        productName: "퓨어 클렌징 오일 200ml",
        price: 18900,
        discount: 35,
        tagX: 48,
        tagY: 52,
        productImage: "/products/kb-manyo-oil.jpg"
      },
      {
        productId: "kb-glint-highlighter",
        brand: "Glint",
        productName: "하이라이터 #01 듀이 문",
        price: 15400,
        discount: 30,
        tagX: 50,
        tagY: 53,
        productImage: "/products/kb-glint-highlighter.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-06-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.6,
        polygonPoints: "44,61 47,59 50,60 53,59 56,61 58,63 54,66 50,67 45,66 42,63",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 63,
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "자연스러운 물먹은 틴트 립",
        appliedEffect: "클렌징 후 가볍게 물들이는 데일리 틴트",
        textureNote: "끈적이지 않는 워터리 글로우"
      },
      {
        id: "zone-kb-06-nose",
        zone: "nose",
        zoneName: "코 / 콧대 (Nose)",
        zoneIcon: "👃",
        confidence: 99.7,
        polygonPoints: "47,44 51,44 53,50 54,54 55,57 51,59 47,57 45,54 46,50",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 50,
        anchorY: 53,
        productId: "kb-glint-highlighter",
        brand: "Glint",
        productName: "하이라이터 #01 듀이 문",
        price: 15400,
        discount: 30,
        productImage: "/products/kb-glint-highlighter.jpg",
        cosmeticRole: "코끝 샴페인 볼륨 광채",
        appliedEffect: "블랙헤드 세정 후 매끈해진 코끝에 펄 하이라이터 포인트",
        textureNote: "모공 부각 없는 투명 펄감"
      },
      {
        id: "zone-kb-06-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.5,
        polygonPoints: "28,42 35,39 42,42 39,46 32,46",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 35,
        anchorY: 42,
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "점막 슬림 아이라인",
        appliedEffect: "점막을 얇게 채워 맑고 선명한 눈매 연출",
        textureNote: "물과 땀에 강한 지속력"
      },
      {
        id: "zone-kb-06-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.4,
        polygonPoints: "26,33 34,30 42,32 41,35 34,33 26,35",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 34,
        anchorY: 32,
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "깔끔한 스트레이트 브로우",
        appliedEffect: "라인을 정교하게 딴 모던 브로우",
        textureNote: "하드 포뮬러 롱래스팅"
      },
      {
        id: "zone-kb-06-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 클렌징 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.8,
        polygonPoints: "26,48 35,44 44,47 44,56 38,64 28,62 23,55",
        fillColor: "rgba(59, 130, 246, 0.35)",
        strokeColor: "rgba(96, 165, 250, 0.95)",
        glowColor: "rgba(59, 130, 246, 0.8)",
        anchorX: 34,
        anchorY: 53,
        productId: "kb-manyo-oil",
        brand: "ma:nyo (마녀공장)",
        productName: "퓨어 클렌징 오일 200ml",
        price: 18900,
        discount: 35,
        productImage: "/products/kb-manyo-oil.jpg",
        cosmeticRole: "모공 속 피지 99.7% 녹이는 롤링 케어",
        appliedEffect: "볼 부위 1분 롤링 후 미온수로 유화 세정",
        textureNote: "산뜻한 친수성 식물성 오일"
      }
    ]
  },
  {
    id: "post-kb-07",
    creatorHandle: "jiwoo.clean",
    creatorName: "지우클린",
    creatorAvatar: "/kbeauty-models/kbeauty-hero-model.jpg",
    modelImage: "/kbeauty-models/kbeauty-hero-model.jpg",
    routineTitle: "피부결 정돈 백탁 0% 선스크린 & 소프트 치크 루틴 ✨",
    caption: "메이크업 전 필수! 백탁 없이 촉촉한 조선미녀 쌀선크림 베이스에 3CE 블러셔로 과하지 않은 생기 얹기.",
    likes: 38200,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-beautiful-woman-putting-on-makeup-41223-large.mp4",
    productTags: [
      {
        productId: "kb-boj-sun",
        brand: "Beauty of Joseon",
        productName: "맑은쌀선크림 SPF50+ PA++++",
        price: 13500,
        discount: 25,
        tagX: 50,
        tagY: 35,
        productImage: "/products/kb-boj-sun.jpg"
      },
      {
        productId: "kb-3ce-blush",
        brand: "3CE",
        productName: "무드 레시피 페이스 블러쉬",
        price: 13500,
        discount: 25,
        tagX: 34,
        tagY: 53,
        productImage: "/products/kb-3ce-blush.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-07-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.8,
        polygonPoints: "44,61.5 47,59.8 50,60.5 53,59.8 56,61.5 58,63.2 55,66.4 50,68 45,66.4 42,63.2",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 64,
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트 #25 베어그레이프",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "맑은 유리알 포도빛 발색",
        appliedEffect: "입술 선을 부드럽게 살린 과즙 립",
        textureNote: "수분 보습 코팅 텍스처"
      },
      {
        id: "zone-kb-07-nose",
        zone: "nose",
        zoneName: "코 / 콧대 (Nose)",
        zoneIcon: "👃",
        confidence: 99.6,
        polygonPoints: "47,43 51,43 52,48 53,54 55,57 51,59 47,57 45,54 46,48",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 49,
        anchorY: 53,
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        productImage: "/products/kb-toocool-shading.jpg",
        cosmeticRole: "자연스러운 음영 콧대 라인",
        appliedEffect: "콧대를 날렵하게 세워주는 3색 블렌딩 쉐딩",
        textureNote: "밀착 파우더 음영"
      },
      {
        id: "zone-kb-07-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.7,
        polygonPoints: "28,42 35,39 42,42 39,46 32,46",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 35,
        anchorY: 42,
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "또렷한 눈매 브라운 아이라인",
        appliedEffect: "점막부터 눈꼬리까지 번짐 없는 라인 연출",
        textureNote: "초슬림 펜 팁"
      },
      {
        id: "zone-kb-07-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.4,
        polygonPoints: "26,34 33,31 42,33 41,36 33,34 26,36",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 34,
        anchorY: 33,
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "입체적인 결 브로우",
        appliedEffect: "눈썹 앞머리 결을 살린 내추럴 브로우",
        textureNote: "뭉침 없는 하드 포뮬러"
      },
      {
        id: "zone-kb-07-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 치크 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.5,
        polygonPoints: "26,48 34,44 42,48 43,56 38,63 29,61 24,54",
        fillColor: "rgba(236, 72, 153, 0.35)",
        strokeColor: "rgba(244, 114, 182, 0.95)",
        glowColor: "rgba(236, 72, 153, 0.8)",
        anchorX: 33,
        anchorY: 53,
        productId: "kb-3ce-blush",
        brand: "3CE",
        productName: "무드 레시피 페이스 블러쉬 #모노핑크",
        price: 13500,
        discount: 25,
        productImage: "/products/kb-3ce-blush.jpg",
        cosmeticRole: "화사한 수채화 핑크 볼륨",
        appliedEffect: "맑은 핑크 컬러를 볼 전체에 은은하게 블러링",
        textureNote: "모공 요철 블러 효과"
      }
    ]
  },
  {
    id: "post-kb-08",
    creatorHandle: "sera.glow",
    creatorName: "세라글로우",
    creatorAvatar: "/kbeauty-models/model-glow-lip.jpg",
    modelImage: "/kbeauty-models/model-glow-lip.jpg",
    routineTitle: "에스테틱 부럽지 않은 메디큐브 홈케어 디바이스 & 풀 페이스 룩",
    caption: "갈바닉 모공 흡수 모드로 기초 싹 먹여주고 투쿨 바이로댕 쉐딩으로 완벽한 V라인 윤곽 완성!",
    likes: 42100,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-close-up-of-a-woman-applying-mascara-39828-large.mp4",
    productTags: [
      {
        productId: "kb-medicube-pro",
        brand: "medicube",
        productName: "에이지알 부스터 프로",
        price: 299000,
        discount: 25,
        tagX: 50,
        tagY: 45,
        productImage: "/products/kb-medicube-pro.jpg"
      },
      {
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        tagX: 48,
        tagY: 54,
        productImage: "/products/kb-toocool-shading.jpg"
      }
    ],
    faceZones: [
      {
        id: "zone-kb-08-lips",
        zone: "lips",
        zoneName: "입술 (Lips)",
        zoneIcon: "💋",
        confidence: 99.8,
        polygonPoints: "44,62 47,60 50,61 53,60 56,62 58,64 54,67 50,68 46,67 42,64",
        fillColor: "rgba(244, 63, 94, 0.40)",
        strokeColor: "rgba(251, 113, 133, 0.95)",
        glowColor: "rgba(244, 63, 94, 0.8)",
        anchorX: 50,
        anchorY: 64,
        productId: "kb-romand-tint",
        brand: "rom&nd",
        productName: "쥬시 래스팅 틴트",
        price: 8900,
        discount: 32,
        productImage: "/products/kb-romand-tint.jpg",
        cosmeticRole: "글래스 볼륨 광택 립",
        appliedEffect: "볼륨 플럼핑 광택 틴트 도포",
        textureNote: "수분 보습 코팅"
      },
      {
        id: "zone-kb-08-nose",
        zone: "nose",
        zoneName: "코 / 콧대 (Nose)",
        zoneIcon: "👃",
        confidence: 99.6,
        polygonPoints: "47,44 51,44 53,50 54,54 55,57 51,59 47,57 45,54 46,50",
        fillColor: "rgba(245, 158, 11, 0.35)",
        strokeColor: "rgba(251, 191, 36, 0.95)",
        glowColor: "rgba(245, 158, 11, 0.8)",
        anchorX: 50,
        anchorY: 53,
        productId: "kb-toocool-shading",
        brand: "too cool for school",
        productName: "아트클래스 바이로댕 쉐딩 마스터",
        price: 11200,
        discount: 30,
        productImage: "/products/kb-toocool-shading.jpg",
        cosmeticRole: "V라인 윤곽 콧대 쉐딩",
        appliedEffect: "턱선과 콧대를 함께 정돈하는 입체 컨투어링",
        textureNote: "초미세 파우더 쉐딩"
      },
      {
        id: "zone-kb-08-eyes",
        zone: "eyes",
        zoneName: "눈 / 아이 (Eyes)",
        zoneIcon: "👁️",
        confidence: 99.7,
        polygonPoints: "28,42 35,39 42,42 39,46 32,46",
        fillColor: "rgba(168, 85, 247, 0.38)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(168, 85, 247, 0.85)",
        anchorX: 35,
        anchorY: 42,
        productId: "kb-clio-liner",
        brand: "CLIO",
        productName: "워터프루프 펜라이너 킬브라운",
        price: 12600,
        discount: 30,
        productImage: "/products/kb-clio-liner.jpg",
        cosmeticRole: "선명한 롱래스팅 아이라인",
        appliedEffect: "눈매를 또렷하게 잡아주는 킬브라운 펜라이너",
        textureNote: "스머지프루프"
      },
      {
        id: "zone-kb-08-eyebrows",
        zone: "eyebrows",
        zoneName: "눈썹 (Eyebrows)",
        zoneIcon: "✏️",
        confidence: 99.5,
        polygonPoints: "26,33 34,30 42,32 41,35 34,33 26,35",
        fillColor: "rgba(16, 185, 129, 0.35)",
        strokeColor: "rgba(52, 211, 153, 0.95)",
        glowColor: "rgba(16, 185, 129, 0.8)",
        anchorX: 34,
        anchorY: 32,
        productId: "kb-etude-brow",
        brand: "ETUDE",
        productName: "드로잉 아이브로우 슬림",
        price: 3500,
        discount: 30,
        productImage: "/products/kb-etude-brow.jpg",
        cosmeticRole: "자연스러운 아치형 눈썹",
        appliedEffect: "결을 살려 한 올 한 올 심은 듯 표현",
        textureNote: "하드 포뮬러"
      },
      {
        id: "zone-kb-08-cheeks",
        zone: "cheeks",
        zoneName: "볼 / 탄력 케어 (Cheeks)",
        zoneIcon: "🌸",
        confidence: 99.8,
        polygonPoints: "26,48 35,44 44,47 44,56 38,64 28,62 23,55",
        fillColor: "rgba(147, 51, 234, 0.35)",
        strokeColor: "rgba(192, 132, 252, 0.95)",
        glowColor: "rgba(147, 51, 234, 0.8)",
        anchorX: 34,
        anchorY: 53,
        productId: "kb-medicube-pro",
        brand: "medicube (메디큐브)",
        productName: "에이지알 부스터 프로",
        price: 299000,
        discount: 25,
        productImage: "/products/kb-medicube-pro.jpg",
        cosmeticRole: "갈바닉 딥 흡수 모드로 콜라겐 탄력 리프팅",
        appliedEffect: "앰플 도포 후 부스터 프로로 양 볼 5분간 마사지",
        textureNote: "미세 전기 자극으로 모공 축소 및 수분 광채"
      }
    ]
  }
];
'''

with open(file_path, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Updated real-products-data.ts successfully")
